package org.debooklog.debooklogserver.mock

import org.debooklog.debooklogserver.core.book.model.Book
import org.debooklog.debooklogserver.core.book.port.BookRepository

class FakeBookRepository : BookRepository {
    private var autoGeneratedId: Long = 0
    private val data: MutableList<Book> = mutableListOf()

    override fun findAllByMemberId(memberId: Long): List<Book> {
        return data.filter { it.memberId == memberId }
    }

    override fun save(book: Book): Book {
        if (book.id == null || book.id == 0L) {
            val newBook =
                Book(
                    id = ++autoGeneratedId,
                    memberId = book.memberId,
                    bookshelfId = book.bookshelfId,
                    title = book.title,
                    author = book.author,
                    isbn = book.isbn,
                    thumbnail = book.thumbnail,
                    likeCount = book.likeCount,
                    state = book.state,
                    createdAt = book.createdAt,
                    updatedAt = book.updatedAt,
                    deletedAt = book.deletedAt,
                    isDeleted = book.isDeleted,
                )
            data.add(newBook)
            return newBook
        } else {
            data.removeIf { it.id == book.id }
            data.add(book)
            return book
        }
    }

    override fun getById(bookId: Long): Book {
        return data.first { it.id == bookId }
    }

    override fun findAllByBookshelfId(bookshelfId: Long): List<Book> {
        return data.filter { it.bookshelfId == bookshelfId }
    }

    override fun findAll(): List<Book> {
        return data
    }
}
